<a href="https://colab.research.google.com/github/laurenchlebove/CS381/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
import pandas as pd

def main():

# Write a Python/NumPy code block that finds the distinct/unique common items between these two
# arrays:

  a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
  b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

  c = np.intersect1d(a, b)
  print(c)
               

# Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
# so that you do not need to explicitly key in every integer value.
# 1   6    11
# 2   7    12
# 3   8    13
# 4   9    14
# 5   10   15 

  a1 = np.transpose(np.arange(1, 16).reshape((3, 5)))  
  print(a1)


# The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”.
# Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values
# contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

  a1_flat = np.transpose(a1).flatten()
  print(a1_flat)


# Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first
# dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column
# becomes the third dimension of the 3-D array.

  a1_3d = a1.reshape(5, 3, 1)


# Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2

  a1_2d = a1_3d.reshape(5, 3)


# You are given the following two arrays:
# a = np.array([12, 5, 7, 15, 3, 1, 8])
# b = np.array([14, 6, 3, 11, 19, 12, 5])
# Write a Python/Numpy code block that removes from array a any items that are also present in array b.


  a2 = np.array([12, 5, 7, 15, 3, 1, 8])
  b2 = np.array([14, 6, 3, 11, 19, 12, 5])

  ab_intersect = np.intersect1d(a2, b2)


# taken from https://thispointer.com/delete-elements-from-a-numpy-array-by-value-or-conditions-in-python/

  for i in ab_intersect:
    a2 = a2[a2 != i]



  nyc_consumption_file = "https://raw.githubusercontent.com/laurenchlebove/CS381/main/Module6_Data.csv"
  df = pd.read_csv(nyc_consumption_file)


# What is the maximum yearly NYC consumption of water in millions of gallons per day?

  max_con = max(list(df["NYC Consumption(Million gallons per day)"]))
  print(max_con)


# How many calendar years are represented within this data set? NumPy's shape command is one way to find out.

  num_years = len(list(df["Year"]))
  print(num_years)


# What is the mean and the standard deviation of the per capita daily water consumption?

  per_cap_mean = np.mean(df["Per Capita(Gallons per person per day)"])
  print(per_cap_mean)

  per_cap_std = np.std(df["Per Capita(Gallons per person per day)"])
  print(per_cap_std)


# What is the increase or decrease in population from year to year? Use NumPy's diff function to create
# an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

  pop_diff = np.diff(df["New York City Population"])

  print("Difference in Population from year to year:")
  print(pop_diff)



if __name__ == '__main__':
  main()

[2 4]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1512.0
39
160.30769230769232
31.51894330370624
Difference in Population from year to year:
[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]


What is the maximum yearly NYC consumption of water in millions of gallons per day?

How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.

What is the mean and the standard deviation of the per capita daily water consumption?

What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.


